[profile.default]
solc = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "script/input/"}
]
optimizer_runs = 1_000_000
verbosity = 3
no_match_coverage = "^script/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
